travis:
  secure:
    BINSTAR_TOKEN: QzXpHkWl8Uz71Mp6wrcxaL1+9s6dm8+bkKIGuYOaynyqFpOYvbF2uaJlS/F1d7ab/iRhh8VVa22+TYNzcltPKrEUdebpOnjNDJruknX1PZSWxJAbVQ3QEjg8BGpBJlD7SXW58VeZzDbFmAnjZKrXKclB1QXafCg3gFwYNZnAMC9lXJmjoZwACHP8mgg3z/8kYHUR9MgwSN9/6L1LM6u+1PGhNOVwy05C8PiOi3kGi7SumoabwjsqaARzex+BD8Ho4FKNIZti+10QaoUayANVGvudyBPwxcbjMNa/obCw/gFZfdtMP2LPBnukaf4xaUK8DBN8jYn6phQD9E5tfZuET+8otfn6Vecie1dr+A8PvWN39eTj1ktzzyTCfoms9LWQJJPJafIPS/rrqvZHEs+O8QQF/qwX1Lf4gNx+3ZK4iX25gpgr48tzOrt4LP1c3EyrxsA5oNS3PNhmh+MgXAOVRhIQ6iWgSH31KOv5Zq3uKSPiP63YuDj+S1TAWuhyoEHwpZpAVHplhb0Lm7h2lR7/rXgYu6j5vT64a5hLz7H1xiVvGzCV+y+Dp8V6IAHix6Rs6HqjvGwXvfNN7GfxDvMxCXCfOkWNhTaR44kowAQp7P9260pS2C8ne9XuMQfRwNKbdL7nXiW6YhuLKiVB046Az97fxBJ85BXZ4ZhOlyvUpBg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
